### ISSUE TITLE
can't find read only form field in sketch

### ISSUE THREAD

**Issue by spike321** [salesforce-ux/design-system-sketch#2]
I see normal,  disabled, error, focus and temporary.  But no read only. Readonly is not supposed to have the box border showing and the text is black and slightly larger than label. I don't see that in the sketch library.  I only see it in the code version online.

**Comment by erlswtshrt** [comment]
Hi @spike321, apologies for the delay on this. You should be able to find this variant by searching "read only" in our "Components: Web" library. You will find it under the input component. See below.

<img width="477" alt="Screen Shot 2021-02-02 at 2 05 49 PM" src="https://user-images.githubusercontent.com/7698220/106669121-08923f00-6560-11eb-9314-7bfc2f61dfd5.png">

If you still cannot find this, make sure you are using our latest UI kits -- update within Sketch if needed.

Closing for now. Please let us know if you need any more help. Thanks!
